name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build (workspace)
        run: cargo build --workspace --release
      - name: Test (workspace)
        run: cargo test --workspace --release
